### PR TITLE
Problem: TOC was malformatted for top-level entries

### PR DESCRIPTION
**Pull request by hintjens**
Caused by incorrect change to TOC code.

Solution: fixed this.

### CODE REVIEW

**Comment by keent** [comment]
@hintjens It seems there are no other maintainers to gitdown, if you liked my previous commits to this project, you can add me as one - Gran

**Comment by hintjens** [comment]
@keent good idea, I've added you as maintainer. Thanks :)

**Comment by keent** [comment]
@hintjens Welcome and thanks. Strange though - I still couldn't see that nice green merge button.

**Comment by hintjens** [comment]
Ah, github's shiny new team management UI defaults to read access on public repos, which is extraordinarily useful... I've set write access now.

**Pull request merged**
